### ISSUE TITLE
Swagger UI giving 404 with the Azure Function 

### ISSUE THREAD

**Issue by kamalbhatia528** [micronaut-projects/micronaut-azure#449]
### Expected Behavior

Swagger UI should work with this link http://localhost:8080/swagger-ui/

### Actual Behaviour

Getting 404 Not found with this link http://localhost:8080/swagger-ui/

### Steps To Reproduce

First generate a new Project with below Link
https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_17&lang=JAVA&build=GRADLE&test=JUNIT&features=openapi&features=swagger-ui&features=azure-function&version=3.8.7

and try to access http://localhost:8080/swagger-ui/, **Its giving 404 Not found.**

### Example Application

https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_17&lang=JAVA&build=GRADLE&test=JUNIT&features=openapi&features=swagger-ui&features=azure-function&version=3.8.7

### Version

3.8.7

**Comment by kamalbhatia528** [comment]
@graemerocher Any update on this issue?

**Comment by sdelamo** [comment]
@Richardson-e Please, verify if this issue is still present in Micronaut Framework 4.

**Comment by sdelamo** [comment]
This is fixed in Micronaut Framework 4. 

[Generate an app with features `swagger-ui` `openapi` and `azure-function`](https://micronaut.io/launch?features=openapi&features=swagger-ui&features=azure-function)

run your application with `./gradlew azureFunctionsRun` and you can access swagger ui at http://localhost:7071/swagger-ui


The fix is probably related to [Function Route Prefix](https://micronaut-projects.github.io/micronaut-azure/5.0.1/guide/index.html#routePrefix) changes
